- README
> Add a readme file

- cards.js
- firebase.js
- gamestate.js
- overlay-terry1.html
- style-terry1.css
Adds HTML and CSS for Terry's initial overlay design.  Syncing of game state to Firebase is in a JS file which should be usable across designs (may require a few tweaks to selectors).
> Terry's overlay

- director.html
- director.js
- gamestate.js
- overlay-ned1.html
- style-ned1.css
Add autocompletion of featured card names to director.html
Store only exact names in firebase, and store one for each player
A featured card name being present will show the card and hide their
hand
gamestate now matches just on exact names
update THE NED to not duplicate html for featured card view
fixes #22
fixes #14
> make featured cards less awful

- cards.js
- gamestate.js
- style-ned1.css
> cards in hand transitions

- director.html
- gamestate.js
- overlay-ned1.html
- style-ned1.css
> implements chyron

- cards.js
- decklistbot/deckimport.js
> split cards import

- cards.js
- decklistbot/deckimport.js
- spotter.js
> improve land detection

- director.css
- director.html
- director.js
- gamestate.js
- overlay-ned1.html
- style-ned1.css
> move freetext into chyron

- gamestate.js
- overlay-ned1.html
> apple emojis

- decklist.css
- decklist.html
- decklist.js
Also move deck name onto its own line to avoid weird wrapping
issues.
> Balance size of columns in decklist view

- cards.js
> fix card animations & make more robust

- director.html
- director.js
- gamestate.js
Change the life total buttons to the more traditional +5/+1/-1/-5.
(Debouncing removes the need for -2 and -3.)
> Add debouncing to life/poison displays.

- director.html
- director.js
- gamestate.js
> adds infinity life

- overlay-ned1.html
- style-ned1.css
> flexify split chyron

- decklistbot/app.js
> use data attributes instead of text when scraping tappedout

- cards.js
- decklistbot/deckimport.js
> populate deckimport.html text areas with current decklist

- css/cards.css
> fix mana symbol alignment

- decklist.css
- decklist.html
- decklistgen/decklist_gen.js
- decklistgen/package.json
> static decklist page generation script

- style.css
> move sideboards and raise featured card z-index

- director.html
- director.js
> add clear hands button to director.js

- index.html
> external links in new window

- overlay-game.html
- overlay-game.js
- style.css
> add test background on alt-T

- css/cards.css
> fix colorless card backgrounds

- assets/css/main.css
- assets/js/main.js
- cards.js
- decklist-2017-03-09.html
- decklist-2017-03-17.html
- decklist.html
> decklist page redesign

- css/mana.css
> darken black mana symbol background color

- decklistbot/deckimport.js
> fix breaking//entering

- decklistbot/deckimport.js
> add card count to decklist import response

- decklist-2017-03-31.html
- decklist.html
- decklistbot/decklist_gen.js
> remove comment from decklist page title

- style.css
> move featured card to top
